<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DemoDataDriven</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>24b1b2e6-f59b-40b3-bc01-dc5a47a2a8c7</testSuiteGuid>
   <testCaseLink>
      <guid>25abbb21-3e48-4113-bbbb-03952f4946e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Set-1/DemoDataDriven</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7f86aee7-bc5d-4769-9578-6d414771cb71</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData2</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>7f86aee7-bc5d-4769-9578-6d414771cb71</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>LoginName</value>
         <variableId>3b9befa4-32f8-4cde-b22e-94df0d7aa05e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7f86aee7-bc5d-4769-9578-6d414771cb71</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>4db0fdea-f626-49b0-b4cc-19c56fb19ec2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
