<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DemoDataDriven_InternalData</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>df65a911-4b05-4368-b1ec-86841cbe1017</testSuiteGuid>
   <testCaseLink>
      <guid>e286509c-f9ba-463c-bc0e-3b9953ed5836</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Set-1/DemoDataDriven</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bc9f91a2-6633-442a-8e98-9e38ec198ebc</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData_Internal</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>bc9f91a2-6633-442a-8e98-9e38ec198ebc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>3b9befa4-32f8-4cde-b22e-94df0d7aa05e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bc9f91a2-6633-442a-8e98-9e38ec198ebc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>4db0fdea-f626-49b0-b4cc-19c56fb19ec2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
